
/* Core includes needed for the gamemode to function */

#include <a_samp>
#include <sscanf2>
#include <zcmd>
#include <zones>
#include <fire>
#include <streamer>
#include <cuffs>
#include <foreach>
#include <a_mysql>
#include <../../include/gl_common>
#include <remove>
#include <abreak>
#include <irc>
#include <SFCNR/files>
#include <progress>

/* Custom includes containing all the gamemodes core functions and systems */

#include <SFCNR\PreprocessorDirectives>
#include <SFCNR\Prototypes>
#include <SFCNR\Variables>
#include <SFCNR\Enumerations>
#include <SFCNR\Arrays>
#include <SFCNR\Functions>
#include <SFCNR\OnGameModeInit>
#include <SFCNR\OnGameModeExit>
#include <SFCNR\MySQL>
#include <SFCNR\Timer>
#include <SFCNR\Ban>
#include <SFCNR\Dynamic>
#include <SFCNR\PEvents>
#include <SFCNR\SEvents>
#include <SFCNR\ClassCMDS>
#include <SFCNR\Irc>
#include <SFCNR\IRCCMDS>
#include <SFCNR\PrivateMessaging>
#include <SFCNR\MiscCMDS>
#include <SFCNR\Animations>
#include <SFCNR\Admin>
#include <SFCNR\TestCMDS>