/*	Beta.inc 
	
	This include was made for the purpose of making San Fierro Cops And Robbers
*/


// admin commands command
/*CMD:acmds(playerid, params[])
{
	if(Spawned[playerid] == false) return SendClientMessage(playerid, COLOR_RED2, "[ERROR] :{FFFFFF} You need to spawn before using any commands.");
	if(PlayerInfo[playerid][Padmin] < 1) return SendClientMessage(playerid, COLOR_RED2, "[ERROR] :{FFFFFF} This command is for staff memebers only!");
	ShowPlayerDialog(playerid, DIALOG_ACMDS, DIALOG_STYLE_MSGBOX, "{FFFFFF}Admin Commands", "{FF0000}[CMD]{FFFFFF} /setlvl -{FF0000} This command is used to set a players admin level\n{FF0000}[CMD]{FFFFFF} /slap -{FF0000} Slaps a player into the air and reduces some health \
	\n{FF0000}[CMD]{FFFFFF} /apm -{FF0000} Send an admin privite message to a player\n{FF0000}[CMD]{FFFFFF} /explode -{FF0000} Create an explosion directly at a player\n{FF0000}[CMD]
	{FFFFFF} /mute -{FF0000} Mutes a player\n{FF0000}[CMD]{FFFFFF} /unmute -{FF0000} UnMutes a player \
	\n{FF0000}[CMD]{FFFFFF} /ann -{FF0000} Annouce a message to everyone", "Ok", "Close");
	return 1;
}*/
